### ISSUE TITLE
EAR backwards compatibility does not work for getItem endpoint.

### ISSUE THREAD

**Issue by danieltruong** [bcgov/eagle-api#343]
When getting a singular project using the search service, I am unable to get the original project format. You are able to recreate this by requesting a project by its ID and making the dataset=item.

**Comment by ActionAnalytics** [comment]
@danieltruong has anyone gotten back to you about this?

**Comment by MaxWardle** [comment]
Hey, looking into this. Updating so dataset=item returns any top level data.

**Comment by MaxWardle** [comment]
After testing I found that the endpoint works as originally intended e.g. http://localhost:3000/api/search?dataset=Item&_schemaName=Project&_id=<some id>. If more functionality is required we can have a conversation about what is needed and make a ticket accordingly.
